# Generated by Django 4.2.10 on 2024-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_video_streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangostreamvideo',
            name='hls_file',
            field=models.FileField(blank=True, null=True, upload_to='hls_videos/'),
        ),
    ]
