# Generated by Django 4.2.10 on 2024-02-14 05:09

import django.core.validators
from django.db import migrations, models
import django_video_streaming.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_video_streaming', '0002_djangostreamvideo_hls_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangostreamvideo',
            name='hls_file',
            field=models.FileField(blank=True, null=True, upload_to=django_video_streaming.models.DjangoStreamVideo.upload_to_path),
        ),
        migrations.AlterField(
            model_name='djangostreamvideo',
            name='video',
            field=models.FileField(upload_to='uploads/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
        migrations.AlterField(
            model_name='segment',
            name='file',
            field=models.FileField(upload_to=django_video_streaming.models.Segment.upload_to_path),
        ),
    ]
