# Generated by Django 4.2.9 on 2024-02-17 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_video_streaming', '0003_alter_djangostreamvideo_hls_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangostreamvideo',
            name='video',
            field=models.FileField(upload_to='django-video-streaming/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
